// Generated by CoffeeScript 1.8.0
var links_ref, msnry, ref;

msnry = null;

ref = new Firebase("https://question-everything.firebaseio.com");

links_ref = new Firebase("https://question-links.firebaseio.com");

$('trix-editor')[0].editor.setSelectedRange([100, 100]);
